steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cellular-axon-325108/worker-louis','./worker']
    id: worker
  - name: 'grc/io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cellular-axon-325108/result-louis','./result']
    id: result
  - name: 'grc/io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cellular-axon-325108/vote-louis','./vote']
    id: vote
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: [result]
    entrypoint : gcloud
    args : 
      - 'run'
      - 'deploy' 
      - 'service-result-louis'
      - '--image'
      - 'gcr.io/cellular-axon-325108/result-louis'
      - '--region'
      - 'europe-west3'
      - '--port'
      - '4000'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: [worker]
    entrypoint : gcloud
    args : 
      - 'run'
      - 'deploy' 
      - 'service-worker-louis'
      - '--image'
      - 'gcr.io/cellular-axon-325108/worker-louis'
      - '--region'
      - 'europe-west3'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: [vote]
    entrypoint : gcloud
    args : 
      - 'run'
      - 'deploy' 
      - 'service-vote-louis'
      - '--image'
      - 'gcr.io/cellular-axon-325108/vote-louis'
      - '--region'
      - 'europe-west3'
      - '--port'
      - '80'
images: ['gcr.io/cellular-axon-325108/worker-louis','gcr.io/cellular-axon-325108/result-louis','gcr.io/cellular-axon-325108/vote-louis']