apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  namespace: global-vote-app-louis
spec:
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: gcr.io/cellular-axon-325108/worker-louis
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        
