apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  namespace: global-vote-app-louis
spec:
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-app
        image: gcr.io/cellular-axon-325108/vote-louis
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
